import type { UiDictionary } from "./types";

export const uiEn: UiDictionary = {
  demo: {
    tag: "Site example",
    banner: "SvojSmeštaj builds websites like this.",
    whatsappCta: "Message us on WhatsApp →",
    packageGroup: "Package",
    languageGroup: "Language",
    basic: "Basic",
    premium: "Premium",
    priceHint: "€499 · one property",
    priceHintPremium: "€900 · up to 5 units",
    dockLabel: "Package preview",
    dockHint: "Compare packages",
    dockOpen: "Open package preview",
    compareCta: "? What’s included in Premium?",
    compareTitle: "What’s included in Premium",
    compareLead:
      "Premium turns your site into a complete direct-booking channel — 0% commission, multi-unit, speed.",
    compareClose: "Close",
    premiumFeatures: [
      "Direct bookings with no Booking/Airbnb commission",
      "Integrated multi-step booking engine",
      "Multi-unit management (Villa, Apartment, Studio)",
      "Google Reviews / Airbnb trust badge",
      "Multi-language support (SR / EN / RU)",
      "SEO & ultra-fast loading",
    ],
  },
  nav: {
    about: "About",
    gallery: "Gallery",
    amenities: "Amenities",
    dates: "Availability",
    contact: "Contact",
    book: "Reserve your stay →",
  },
  gallery: {
    showAll: "Show all photos",
    open: "Open gallery",
    dialog: "Photo gallery",
    close: "Close",
    prev: "Previous photo",
    next: "Next photo",
  },
  calendar: {
    prevMonth: "Previous month",
    nextMonth: "Next month",
    free: "available",
    busy: "booked",
    months: [
      "January",
      "February",
      "March",
      "April",
      "May",
      "June",
      "July",
      "August",
      "September",
      "October",
      "November",
      "December",
    ],
    days: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
  },
  availability: {
    heading: "Available dates",
    lead: "Check availability for your dates. The calendar shows current occupancy.",
  },
  booking: {
    contactOnlyTitle: "Book directly with the host",
    contactOnlyBody:
      "This website is meant for direct contact with the host. There is no online booking engine or payment on the site — arrange dates by phone, WhatsApp, or email.",
    checkAvailability: "Check dates →",
    sendInquiry: "Send an inquiry",
    sectionHeading: "Reservation",
    steps: {
      unit: "Stay",
      dates: "Dates",
      guests: "Guests",
      review: "Review",
    },
    progressLabel: "Reservation steps",
    back: "Back",
    continue: "Continue",
    confirm: "Confirm",
    selectUnit: "Select",
    selected: "Selected",
    viewPhotos: "View photos",
    chooseThis: "Choose this stay",
    closePreview: "Close",
    guestsLabel: "guests",
    bedrooms: "bedrooms",
    bathrooms: "bathrooms",
    size: "m²",
    beds: "Beds",
    capacity: "Capacity",
    fromPrice: "from",
    perNight: "/ night",
    amenities: "Amenities",
    checkIn: "Check-in",
    checkOut: "Check-out",
    nights: "Nights",
    nightOne: "1 night",
    nightMany: "{n} nights",
    selectCheckIn: "Select your check-in date",
    selectCheckOut: "Then select your check-out date",
    selectCheckInShort: "Add date",
    selectCheckOutShort: "Add date",
    clearDates: "Clear dates",
    rangeBlocked: "That range includes unavailable dates. Please choose another.",
    summary: "Stay summary",
    estimatedTotal: "Estimated total",
    adults: "Adults",
    children: "Children",
    guests: "Guests",
    specialRequest: "Type of celebration",
    specialRequestHint: "e.g. birthday, wedding, anniversary…",
    occupancyHint: "Maximum {n} guests for this stay.",
    occupancyError: "Guest count exceeds the capacity of the selected stay.",
    guestDetails: "Your details",
    fullName: "Full name",
    email: "Email",
    phone: "Phone",
    reviewTitle: "Review reservation",
    reviewLead: "Please check the details before sending your request.",
    notes: "Celebration",
    noNotes: "Not specified",
    successTitle: "Reservation request received",
    successLead: "Thank you for choosing Villa Charm.",
    successBody:
      "Your reservation request has been received. We will contact you shortly to confirm availability and finalize the details.",
    successClose: "Close",
    newRequest: "New reservation",
    estimatedStay: "Estimated stay total",
    inquireSelected: "Inquire for these dates",
  },
  units: {
    heading: "Our stays",
    lead: "Three units on the same grounds — pick the one that fits you.",
    details: "View details",
    bookThis: "Book this stay",
  },
  agency: {
    kicker: "SvojSmeštaj · websites for independent hosts",
    heading: "Your property can look like this",
    body: "Everything above is an example. We can build the same site with your photos, prices, and phone number — guests contact you directly, with no Booking or Airbnb commission.",
    whatsapp: "Message us on WhatsApp",
    colophon: "Demo page — property, names, and contacts are fictional.",
    madeBy: "Built by",
    region: "Serbia",
    benefits: [
      "Direct bookings with no commission",
      "Ultra-fast and SEO-ready",
      "100% mobile support",
    ],
  },
  contact: {
    phone: "Phone",
    whatsapp: "WhatsApp / Viber",
    email: "Email",
    instagram: "Instagram",
  },
  reviews: {
    googleBadge: "Google Maps Rating {score} ★★★★★ ({count} reviews)",
  },
  a11y: {
    mainNav: "Main navigation",
    rating: "Rating {n} of 5",
    menuOpen: "Open menu",
    menuClose: "Close menu",
  },
};
