import type { UiDictionary } from "./types";

export const uiRu: UiDictionary = {
  demo: {
    tag: "Пример сайта",
    banner: "агентство SvojSmeštaj делает такие сайты.",
    whatsappCta: "Напишите нам в WhatsApp →",
    packageGroup: "Пакет",
    languageGroup: "Язык",
    basic: "Basic",
    premium: "Premium",
    priceHint: "499€ · один объект",
    priceHintPremium: "900€ · до 5 объектов",
    dockLabel: "Просмотр пакета",
    dockHint: "Сравнить пакеты",
    dockOpen: "Открыть просмотр пакета",
    compareCta: "? Что входит в Premium?",
    compareTitle: "Что входит в Premium",
    compareLead:
      "Premium превращает ваш сайт в полноценный канал прямых бронирований — 0% комиссии, несколько объектов, скорость.",
    compareClose: "Закрыть",
    premiumFeatures: [
      "Прямые бронирования без комиссии Booking/Airbnb",
      "Встроенный многошаговый движок бронирования",
      "Управление несколькими объектами (Вилла, Апартаменты, Студия)",
      "Google Reviews / Airbnb trust badge",
      "Мультиязычность (SR / EN / RU)",
      "SEO и сверхбыстрая загрузка",
    ],
  },
  nav: {
    about: "Об объекте",
    gallery: "Галерея",
    amenities: "Удобства",
    dates: "Даты",
    contact: "Контакты",
    book: "Забронировать →",
  },
  gallery: {
    showAll: "Показать все фото",
    open: "Открыть галерею",
    dialog: "Фотогалерея",
    close: "Закрыть",
    prev: "Предыдущее фото",
    next: "Следующее фото",
  },
  calendar: {
    prevMonth: "Предыдущий месяц",
    nextMonth: "Следующий месяц",
    free: "свободно",
    busy: "занято",
    months: [
      "январь",
      "февраль",
      "март",
      "апрель",
      "май",
      "июнь",
      "июль",
      "август",
      "сентябрь",
      "октябрь",
      "ноябрь",
      "декабрь",
    ],
    days: ["пн", "вт", "ср", "чт", "пт", "сб", "вс"],
  },
  availability: {
    heading: "Свободные даты",
    lead: "Проверьте доступность на нужные даты. Календарь показывает текущую занятость.",
  },
  booking: {
    contactOnlyTitle: "Бронирование напрямую у хозяина",
    contactOnlyBody:
      "Этот сайт предназначен для прямого контакта с хозяином. Онлайн-бронирования и оплаты на сайте нет — согласуйте даты по телефону, WhatsApp или email.",
    checkAvailability: "Смотреть даты →",
    sendInquiry: "Отправить запрос",
    sectionHeading: "Бронирование",
    steps: {
      unit: "Объект",
      dates: "Даты",
      guests: "Гости",
      review: "Проверка",
    },
    progressLabel: "Шаги бронирования",
    back: "Назад",
    continue: "Далее",
    confirm: "Подтвердить",
    selectUnit: "Выбрать",
    selected: "Выбрано",
    viewPhotos: "Смотреть фото",
    chooseThis: "Выбрать этот объект",
    closePreview: "Закрыть",
    guestsLabel: "гостей",
    bedrooms: "спальни",
    bathrooms: "ванные",
    size: "м²",
    beds: "Кровати",
    capacity: "Вместимость",
    fromPrice: "от",
    perNight: "/ ночь",
    amenities: "Удобства",
    checkIn: "Заезд",
    checkOut: "Выезд",
    nights: "Ночи",
    nightOne: "1 ночь",
    nightMany: "{n} ночей",
    selectCheckIn: "Выберите дату заезда",
    selectCheckOut: "Затем выберите дату выезда",
    selectCheckInShort: "Добавить дату",
    selectCheckOutShort: "Добавить дату",
    clearDates: "Очистить даты",
    rangeBlocked: "В выбранном периоде есть занятые даты. Выберите другой диапазон.",
    summary: "Итог проживания",
    estimatedTotal: "Ориентировочная сумма",
    adults: "Взрослые",
    children: "Дети",
    guests: "Гости",
    specialRequest: "Тип праздника",
    specialRequestHint: "Напр. день рождения, свадьба, годовщина…",
    occupancyHint: "Максимум {n} гостей для этого объекта.",
    occupancyError: "Число гостей превышает вместимость выбранного объекта.",
    guestDetails: "Ваши данные",
    fullName: "Имя и фамилия",
    email: "Email",
    phone: "Телефон",
    reviewTitle: "Проверка бронирования",
    reviewLead: "Проверьте детали перед отправкой запроса.",
    notes: "Тип праздника",
    noNotes: "Не указано",
    successTitle: "Запрос на бронирование получен",
    successLead: "Спасибо, что выбрали Villa Charm.",
    successBody:
      "Ваш запрос получен. Мы скоро свяжемся, чтобы подтвердить доступность и согласовать детали.",
    successClose: "Закрыть",
    newRequest: "Новое бронирование",
    estimatedStay: "Ориентировочная стоимость",
    inquireSelected: "Запросить эти даты",
  },
  units: {
    heading: "Наше размещение",
    lead: "Три объекта на одной территории — выберите подходящий.",
    details: "Подробнее",
    bookThis: "Забронировать",
  },
  agency: {
    kicker: "SvojSmeštaj · сайты для независимых хозяев",
    heading: "Ваш объект может выглядеть так",
    body: "Всё выше — пример. Сделаем такой же сайт с вашими фото, ценами и телефоном — гости пишут вам напрямую, без комиссии Booking и Airbnb.",
    whatsapp: "Напишите нам в WhatsApp",
    colophon: "Демо-страница — объект, имена и контакты вымышлены.",
    madeBy: "Сделано",
    region: "Сербия",
    benefits: [
      "Прямые бронирования без комиссии",
      "Сверхбыстрый и SEO-готовый",
      "100% мобильная поддержка",
    ],
  },
  contact: {
    phone: "Телефон",
    whatsapp: "WhatsApp / Viber",
    email: "Email",
    instagram: "Instagram",
  },
  reviews: {
    googleBadge: "Рейтинг Google Maps {score} ★★★★★ ({count} отзывов)",
  },
  a11y: {
    mainNav: "Основная навигация",
    rating: "Оценка {n} из 5",
    menuOpen: "Открыть меню",
    menuClose: "Закрыть меню",
  },
};
