import type { UiDictionary } from "./types";

export const uiSr: UiDictionary = {
  demo: {
    tag: "Primer sajta",
    banner: "agencija SvojSmeštaj pravi ovakve sajtove.",
    whatsappCta: "Piši nam na WhatsApp →",
    packageGroup: "Paket",
    languageGroup: "Jezik",
    basic: "Basic",
    premium: "Premium",
    priceHint: "499€ · jedan objekat",
    priceHintPremium: "900€ · do 5 jedinica",
    dockLabel: "Prikaz paketa",
    dockHint: "Uporedi pakete",
    dockOpen: "Otvori prikaz paketa",
    compareCta: "? Šta uključuje Premium?",
    compareTitle: "Šta uključuje Premium",
    compareLead:
      "Premium paket pretvara vaš sajt u kompletan kanal za direktne rezervacije — 0% provizije, više jedinica, brzina.",
    compareClose: "Zatvori",
    premiumFeatures: [
      "Direktne rezervacije bez Booking/Airbnb provizije",
      "Integrisani višestepeni booking engine",
      "Upravljanje više jedinica (Vila, Apartman, Studio)",
      "Google Reviews / Airbnb trust bedž",
      "Višejezična podrška (SR / EN)",
      "SEO i ultra-brzo učitavanje",
    ],
  },
  nav: {
    about: "O smeštaju",
    gallery: "Galerija",
    amenities: "Sadržaji",
    dates: "Termini",
    contact: "Kontakt",
    book: "Rezerviši boravak →",
  },
  gallery: {
    showAll: "Prikaži sve fotografije",
    open: "Otvori galeriju",
    dialog: "Galerija fotografija",
    close: "Zatvori",
    prev: "Prethodna fotografija",
    next: "Sledeća fotografija",
  },
  calendar: {
    prevMonth: "Prethodni mesec",
    nextMonth: "Sledeći mesec",
    free: "slobodno",
    busy: "zauzeto",
    months: [
      "januar",
      "februar",
      "mart",
      "april",
      "maj",
      "jun",
      "jul",
      "avgust",
      "septembar",
      "oktobar",
      "novembar",
      "decembar",
    ],
    days: ["pon", "uto", "sre", "čet", "pet", "sub", "ned"],
  },
  availability: {
    heading: "Slobodni termini",
    lead: "Proverite dostupnost za željeni period. Kalendar prikazuje trenutnu zauzetost.",
  },
  booking: {
    contactOnlyTitle: "Rezervacija direktno kod domaćina",
    contactOnlyBody:
      "Ovaj sajt je namenjen direktnom kontaktu sa domaćinom. Nema online rezervacije ni plaćanja na sajtu — dogovorite termin telefonom, WhatsApp-om ili e-mailom.",
    checkAvailability: "Proveri dostupnost →",
    sendInquiry: "Pošaljite upit",
    sectionHeading: "Rezervacija",
    sectionLead: "Izaberite smeštaj, datume i goste — mi ćemo potvrditi u najkraćem roku.",
    steps: {
      unit: "Smeštaj",
      dates: "Datumi",
      guests: "Gosti",
      review: "Pregled",
    },
    progressLabel: "Korak rezervacije",
    back: "Nazad",
    continue: "Nastavi",
    confirm: "Potvrdi rezervaciju",
    selectUnit: "Izaberite",
    selected: "Izabrano",
    viewPhotos: "Pogledaj fotografije",
    chooseThis: "Izaberi ovaj smeštaj",
    closePreview: "Zatvori",
    guestsLabel: "gostiju",
    bedrooms: "spavaće sobe",
    bathrooms: "kupatila",
    size: "m²",
    beds: "Kreveti",
    capacity: "Kapacitet",
    fromPrice: "od",
    perNight: "/ noć",
    amenities: "Sadržaji",
    checkIn: "Prijava",
    checkOut: "Odjava",
    nights: "Noći",
    nightOne: "1 noć",
    nightMany: "{n} noći",
    selectCheckIn: "Izaberite datum prijave",
    selectCheckOut: "Zatim izaberite datum odjave",
    selectCheckInShort: "Dodajte datum",
    selectCheckOutShort: "Dodajte datum",
    clearDates: "Obriši datume",
    rangeBlocked: "Izabrani period uključuje zauzete datume. Izaberite drugi raspon.",
    summary: "Pregled boravka",
    estimatedTotal: "Okvirna cena",
    adults: "Odrasli",
    children: "Deca",
    guests: "Gosti",
    specialRequest: "Poseban zahtev",
    specialRequestHint: "Npr. kasni dolazak, krevetac, transfer…",
    occupancyHint: "Maksimalno {n} gostiju za ovaj smeštaj.",
    occupancyError: "Broj gostiju premašuje kapacitet izabranog smeštaja.",
    guestDetails: "Vaši podaci",
    fullName: "Ime i prezime",
    email: "E-mail",
    phone: "Telefon",
    reviewTitle: "Pregled rezervacije",
    reviewLead: "Proverite detalje pre slanja zahteva.",
    notes: "Napomena",
    noNotes: "Bez napomene",
    successTitle: "Zahtev za rezervaciju je primljen",
    successLead: "Hvala što ste izabrali Villa Charm.",
    successBody:
      "Vaš zahtev je uspešno primljen. Javićemo vam se ubrzo da potvrdimo dostupnost i dogovorimo detalje boravka.",
    successClose: "Zatvori",
    newRequest: "Nova rezervacija",
    estimatedStay: "Okvirna cena boravka",
    inquireSelected: "Pošaljite upit za ove datume",
  },
  units: {
    heading: "Naš smeštaj",
    lead: "Tri jedinice na istom imanju — izaberite onu koja vam odgovara.",
    details: "Detaljnije",
    bookThis: "Rezerviši ovaj smeštaj",
  },
  agency: {
    kicker: "SvojSmeštaj · izrada sajtova za izdavaoce",
    heading: "Vaš smeštaj može ovako da izgleda",
    body: "Sve što ste videli iznad je primer. Napravimo vam isti ovakav sajt sa vašim slikama, vašim cenama i vašim brojem telefona — gosti vas zovu direktno, bez provizije Bookingu i Airbnb-u.",
    whatsapp: "Pišite nam na WhatsApp",
    colophon: "Demo stranica — smeštaj, imena i kontakti su izmišljeni.",
    madeBy: "Izradio",
    region: "Srbija",
    benefits: [
      "Direktne rezervacije bez provizije",
      "Ultra-brz i SEO optimizovan",
      "Mobilna podrška 100%",
    ],
  },
  contact: {
    phone: "Telefon",
    whatsapp: "WhatsApp / Viber",
    email: "E-mail",
    instagram: "Instagram",
  },
  reviews: {
    googleBadge: "Google Maps Ocena {score} ★★★★★ ({count} recenzija)",
  },
  a11y: {
    mainNav: "Glavna navigacija",
    rating: "Ocena {n} od 5",
    menuOpen: "Otvori meni",
    menuClose: "Zatvori meni",
  },
};
